services:
  - type: static
    name: mern-movie-frontend
    env: static
    branch: main        # Nh√°nh deploy
    buildCommand: npm install --prefix vite-react-ts-client && npm run build --prefix vite-react-ts-client
    publishPath: vite-react-ts-client/dist
    autoDeploy: true
